### ISSUE TITLE
Update to latest ftc_app release

### ISSUE THREAD

**Issue by TeamTorch5942** [lasarobotics/FTCAndroidLibrary#46]
Hi, ftc_app was just updated. will you guys be updating your repo too?

**Comment by smo-key** [comment]
Yes, we will be updating as soon as we test the updates made to ftc_app and make the necessary upgrades. (We will release this update to master as soon as the library is ready for a version upgrade.)

Since our team is currently at competition and unable to test, any help would be appreciated - if you or any other team wishes to contribute, fork this repository, upgrade the app, test what you can and create a pull request. That way, you get what you need and can also contribute back to the project!

Thanks!
smo-key :bear: and LASA Robotics

**Comment by smo-key** [comment]
@TeamTorch5942 We updated the app to the most recent February 9th release in the `dev` branch. Once the library is completely stable and reviewed, the changes will move to `master`. However, you can upgrade to the `dev` branch if you would like.

**Comment by TeamTorch5942** [comment]
@smo-key I think I misunderstood a few things, so I've got some questions if you don't mind. Thanks for your help developing this library, its been super helpful for our team.
1. I meant the march update, but looking at it again it looks like only the beta ftc_app branch was updated, and there were no updates to master in march, is this correct? 
2. Do you have a rough estimate of when you'll be updating your master? We'd rather not use dev unless we have to since we don't have much time to test it.
3. We go to West Supers next week, which is why I'm bugging you all about this now :stuck_out_tongue_winking_eye:, will we need the newest ftc_app version? What did you guys do at South?

**Comment by smo-key** [comment]
1. Yes, no updates to the stable FIRST SDK in March. However, beta updates are constantly being released.
2. There are a few features we have to finalize and test before the next release. The next release could be as early as today or as late as two weeks from now. We too prefer to keep `master` really stable and so we won't release until changes are tested.
3. I would _strongly recommend_ upgrading your app to the latest stable build prior to any major competition. 4290 (my team) migrated to the most recent version in a highly developmental repo. Most everything worked, but a few bug fixes had to be made - currently, there are no known issues with the compatibility between FTCLib and the stable FIRST apps as all known issues were fixed in the most recent `dev` branch. However, I would also not just upgrade to the `dev` branch unless you have to. **If the only thing you want to change is upgrading the app, here is the process overview:**

### Upgrading FTCLibrary to the latest version on ftc_app
1. Clone `ftc_app` and `git checkout [branch]`, where `[branch]` is either `master` (highly recommended) or `beta`.
2. Copy the contents of the `FtcRobotController/libs/` folder from `ftc_app` into your Robot Controller's `libs/` folder (overwrite any files inside).
3. Copy the `FtcRobotControllerActivity.java` from `FtcRobotController/src/main/java/com/qualcomm/ftcrobotcontroller/FtcRobotControllerActivity.java` and replace your local copy.
4. _(Optional)_ Copy any desired samples from `FtcRobotController/src/main/java/com/qualcomm/ftcrobotcontroller/opmodes` to your OpMode directory (we use the `opmodes/first` folder inside robot controller in the `/sample` in FTCLib. _This step often causes some issues as some opmodes are not compatible. It is generally safe to delete or comment out these opmodes so that they do not interfere with the build._
5. Click `File > Restart and Invalidate Caches` (this may take a few minutes) then attempt to build the app. _Issues may occur due to incompatibility. Should any arise, you will need to fix these manually on a case-by-case basis._

Let us know how this works out,
smo-key :bear:

**Comment by TeamTorch5942** [comment]
Hi @smo-key, we followed your instructions and the app compiles correctly, but opening settings on the robot controller crashes the app. Any idea what's causing it?

Edit: fixed by uninstalling the driver station app on our robot controller phone. Not sure why that was an issue, but everything seems to be fine now.

**Comment by smo-key** [comment]
@TeamTorch5942 I figured out why that issue happens - the underlying issue is that if two apps with differing versions of Qualcomm's libraries are on the phone, then the app doesn't know which version to open. It is also **VERY BAD** to have any two apps with Qualcomm's libs on a single phone. (One of our teams didn't advance partly because the conflicts caused our robot to immediately lose connection - by the time we figured it out, it was too late.)

Hope y'all did well at Supers! Good work figuring that out. We'll roll out another release soon.
smo-key :bear:
